export const people = [
    {
      id: '64af165d5c89aa3e0e6c0dba',
      guestName: 'Cift',
      checkInDate: '',
      checkOutDate: '',
      price: '45',
      imageUrl: 'https://cf.bstatic.com/xdata/images/hotel/max1024x768/211722857.jpg?k=bb5ee4cd953b0a1e17625ef2c3b4d24170e028ae5ed5ee8a5d17d329abd0a0d8&o=&hp=1',
      description: 'Dhome me krevat dopio + ballkon + tv","name":"familjare dhome',
    },
    {
      _id: '2',
      name: 'C-3PO',
      height: '167',
      mass: '75',
      hair_color: 'n/a',
      skin_color: 'gold',
      eye_color: 'yellow',
      gender: 'n/a',
    },
    {
      _id: '3',
      name: 'R2-D2',
      height: '96',
      mass: '32',
      hair_color: 'n/a',
      skin_color: 'white, blue',
      eye_color: 'red',
      gender: 'n/a',
    },
    {
      _id: '4',
      name: 'Darth Vader',
      height: '202',
      mass: '136',
      hair_color: 'none',
      skin_color: 'white',
      eye_color: 'yellow',
      gender: 'male',
    },
    {
      _id: '5',
      name: 'Leia Organa',
      height: '150',
      mass: '49',
      hair_color: 'brown',
      skin_color: 'light',
      eye_color: 'brown',
      gender: 'female',
    },
    {
      _id: '6',
      name: 'Owen Lars',
      height: '178',
      mass: '120',
      hair_color: 'brown, grey',
      skin_color: 'light',
      eye_color: 'blue',
      gender: 'male',
    },
    {
      _id: '7',
      name: 'Beru Whitesun Lars',
      height: '165',
      mass: '75',
      hair_color: 'brown',
      skin_color: 'light',
      eye_color: 'blue',
      gender: 'female',
    },
    {
      _id: '8',
      name: 'R5-D4',
      height: '97',
      mass: '32',
      hair_color: 'n/a',
      skin_color: 'white, red',
      eye_color: 'red',
      gender: 'n/a',
    },
    
  ]


